name: OWASP Dependency-Check

on:
  push:
    branches: 
        - main
    tags:
       - 'v*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: 
        - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "MiProyecto"
          format: "HTML"
          out: "dependency-check-report"

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
      
      - name: Upload report to DefectDojo
        run: |
          curl -k -X POST "$DOJO_HOST/api/v2/import-scan/" \
            -H "Authorization: Token $DOJO_API_KEY" \
            -F "scan_type=Dependency Check Scan" \
            -F "minimum_severity=Low" \
            -F "active=true" \
            -F "verified=true" \
            -F "scan_date=$(date +%F)" \
            -F "engagement=$DOJO_ENGAGEMENT_ID" \
            -F "file=@dependency-check-report/dependency-check-report.xml"
        env:
          DOJO_HOST: ${{ secrets.DEFECTDOJO_HOST }}
          DOJO_API_KEY: ${{ secrets.DEFECTDOJO_API_KEY }}
          DOJO_ENGAGEMENT_ID: ${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}
