name: SonarQube Analysis

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    env:
      SONAR_PROJECT_KEY: Sec-Team-2_mideporte
      SONAR_HOST_URL: https://sonarcloud.io 
  
    services:
        mysql:
            image: mysql:5.7
            env:
              MYSQL_ROOT_PASSWORD: mideporte_root_password
              MYSQL_DATABASE: mideportedb
              MYSQL_USER: mideporte_user
              MYSQL_PASSWORD: mideporte_password
            ports:
              - 3306:3306
            options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          coverage run --source=backend backend/manage.py test
          coverage xml -o coverage-backend.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # --- PASOS PARA INTEGRACIÓN CON DEFECTDOJO ---

      - name: Obtener Informe de Issues de SonarCloud API
        id: get_sonar_issues
        run: |
          # ... (sleep, echo, API_URL, etc.) ...
          curl -s --fail -u "${{ secrets.SONAR_TOKEN }}:" \
            "$API_URL" \
            -o sonarcloud-issues.json

          echo "Comando curl finalizado. Código de salida: $?"
          echo "--- DEBUG: Comprobando archivo generado ---"
          ls -l sonarcloud-issues.json # Muestra si existe y el tamaño
          echo "--- DEBUG: Primeras 10 líneas del archivo ---"
          head -n 10 sonarcloud-issues.json # Muestra el inicio del contenido
          echo "--- FIN DEBUG ---"

          if [ ! -s sonarcloud-issues.json ]; then
            echo "Error: El archivo sonarcloud-issues.json no se creó o está vacío."
            exit 1
          else
            echo "Archivo sonarcloud-issues.json generado correctamente."
          fi

      - name: Cargar Informe a DefectDojo API
        # Asegúrate que DEFECTDOJO_HOST incluye http:// o https:// y el puerto si no es estándar
        # Ejemplo: http://tu-ip-publica:8080 o https://defectdojo.tu-dominio.com
        run: |
          echo "Cargando informe a DefectDojo (${{ secrets.DEFECTDOJO_HOST }})..."
          curl -X POST "${{ secrets.DEFECTDOJO_HOST }}/api/v2/import-scan/" \
            -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
            -F "scan_type=SonarQube API Import" \
            -F "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}" \
            -F "file=@sonarcloud-issues.json" \
            -F "active=true" \
            -F "verified=true" \
            --fail # Falla si la respuesta HTTP es un error (4xx/5xx)
          echo "Carga a DefectDojo completada (o fallida si curl devolvió error)."